app:
  name: SecKill App
  port: :3000

# Database config is not used in Phase A (SPSC Benchmark)
# database:
#   host: localhost
#   port: :3306
#   user: your_name
#   password: your_password
#   name: seckill_db