version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    container_name: seckill-redis
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seckill
    ports:
      - "5432:5432"
    container_name: seckill-postgres
    restart: always
